<a href="https://colab.research.google.com/github/nesbita/ML-Collision-Severity-YOLO-Detection/blob/main/Ariana_Nesbit_Ass2_T22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -U ultralytics
from ultralytics import YOLO
import torch
print('GPU available:', torch.cuda.is_available())
print('Device:', torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU')

Requirement already satisfied: ultralytics in /usr/local/lib/python3.12/dist-packages (8.4.116)
Requirement already satisfied: filelock>=3.16.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (3.29.7)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (3.10.0)
Requirement already satisfied: opencv-python!=4.13.0.90,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (5.0.0.93)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (11.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.32.4)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.11.0+cu128)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (0.26.0+cu128)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (5.9.5)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (1.35.2)
Requirement already satisfied: nvidia-ml-py>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (13.610.43)
Requirement already satisfied: ultralytics-thop>=2.1.6 in /usr/local/lib/python3.12/dist-packages (from ultralytics) (2.1.6)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (26.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.12/dist-packages (from polars>=0.20.0->ultralytics) (1.35.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.23.0->ultralytics) (2026.6.17)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->ultralytics) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.8.0->ultralytics) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.8.0->ultralytics) (1.5.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.3)
GPU available: True
Device: Tesla T4

In [ ]:
from google.colab import drive
import shutil
import os

drive.mount('/content/drive')

DATASET_PATH = '/content/drive/MyDrive/kitti3k_yolo'
CAR_ONLY_PATH = '/content/drive/MyDrive/kitti3k_car_only'

shutil.copytree(DATASET_PATH, '/content/kitti3k_yolo')
print('Dataset copied to local storage.')
print(os.listdir('/content/kitti3k_yolo'))

Mounted at /content/drive
Dataset copied to local storage.
['images', 'kitti3k.yaml', 'labels']

In [ ]:
dataset_yaml = '/content/kitti3k_yolo/kitti3k.yaml'

## 1st CONFIGURATION
model_config1 = YOLO('yolo11n.pt')

train_results1 = model_config1.train(
    data=dataset_yaml,
    epochs=20,
    imgsz=640,
    batch=16,
    lr0=0.001,
    freeze=10,
    workers=2,
    cache='ram',
    device=0,
    exist_ok=True,
    pretrained=True
)

print('Configuration 1 training complete.')

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo11n.pt to 'yolo11n.pt': 100% ━━━━━━━━━━━━ 5.4MB 63.6MB/s 0.1s
Ultralytics 8.4.116 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=ram, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/kitti3k_yolo/kitti3k.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=20, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=10, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.001, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/runs/detect/train, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 23.3MB/s 0.0s
Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    431257  ultralytics.nn.modules.head.Detect           [3, 16, None, [64, 128, 256]]
YOLO11n summary: 182 layers, 2,590,425 parameters, 2,590,409 gradients, 6.5 GFLOPs

Remapped 1/3 cls head rows from pretrained weights by class name
Transferred 451/499 items from pretrained weights
Freezing layer 'model.0.conv.weight'
Freezing layer 'model.0.bn.weight'
Freezing layer 'model.0.bn.bias'
Freezing layer 'model.1.conv.weight'
Freezing layer 'model.1.bn.weight'
Freezing layer 'model.1.bn.bias'
Freezing layer 'model.2.cv1.conv.weight'
Freezing layer 'model.2.cv1.bn.weight'
Freezing layer 'model.2.cv1.bn.bias'
Freezing layer 'model.2.cv2.conv.weight'
Freezing layer 'model.2.cv2.bn.weight'
Freezing layer 'model.2.cv2.bn.bias'
Freezing layer 'model.2.m.0.cv1.conv.weight'
Freezing layer 'model.2.m.0.cv1.bn.weight'
Freezing layer 'model.2.m.0.cv1.bn.bias'
Freezing layer 'model.2.m.0.cv2.conv.weight'
Freezing layer 'model.2.m.0.cv2.bn.weight'
Freezing layer 'model.2.m.0.cv2.bn.bias'
Freezing layer 'model.3.conv.weight'
Freezing layer 'model.3.bn.weight'
Freezing layer 'model.3.bn.bias'
Freezing layer 'model.4.cv1.conv.weight'
Freezing layer 'model.4.cv1.bn.weight'
Freezing layer 'model.4.cv1.bn.bias'
Freezing layer 'model.4.cv2.conv.weight'
Freezing layer 'model.4.cv2.bn.weight'
Freezing layer 'model.4.cv2.bn.bias'
Freezing layer 'model.4.m.0.cv1.conv.weight'
Freezing layer 'model.4.m.0.cv1.bn.weight'
Freezing layer 'model.4.m.0.cv1.bn.bias'
Freezing layer 'model.4.m.0.cv2.conv.weight'
Freezing layer 'model.4.m.0.cv2.bn.weight'
Freezing layer 'model.4.m.0.cv2.bn.bias'
Freezing layer 'model.5.conv.weight'
Freezing layer 'model.5.bn.weight'
Freezing layer 'model.5.bn.bias'
Freezing layer 'model.6.cv1.conv.weight'
Freezing layer 'model.6.cv1.bn.weight'
Freezing layer 'model.6.cv1.bn.bias'
Freezing layer 'model.6.cv2.conv.weight'
Freezing layer 'model.6.cv2.bn.weight'
Freezing layer 'model.6.cv2.bn.bias'
Freezing layer 'model.6.m.0.cv1.conv.weight'
Freezing layer 'model.6.m.0.cv1.bn.weight'
Freezing layer 'model.6.m.0.cv1.bn.bias'
Freezing layer 'model.6.m.0.cv2.conv.weight'
Freezing layer 'model.6.m.0.cv2.bn.weight'
Freezing layer 'model.6.m.0.cv2.bn.bias'
Freezing layer 'model.6.m.0.cv3.conv.weight'
Freezing layer 'model.6.m.0.cv3.bn.weight'
Freezing layer 'model.6.m.0.cv3.bn.bias'
Freezing layer 'model.6.m.0.m.0.cv1.conv.weight'
Freezing layer 'model.6.m.0.m.0.cv1.bn.weight'
Freezing layer 'model.6.m.0.m.0.cv1.bn.bias'
Freezing layer 'model.6.m.0.m.0.cv2.conv.weight'
Freezing layer 'model.6.m.0.m.0.cv2.bn.weight'
Freezing layer 'model.6.m.0.m.0.cv2.bn.bias'
Freezing layer 'model.6.m.0.m.1.cv1.conv.weight'
Freezing layer 'model.6.m.0.m.1.cv1.bn.weight'
Freezing layer 'model.6.m.0.m.1.cv1.bn.bias'
Freezing layer 'model.6.m.0.m.1.cv2.conv.weight'
Freezing layer 'model.6.m.0.m.1.cv2.bn.weight'
Freezing layer 'model.6.m.0.m.1.cv2.bn.bias'
Freezing layer 'model.7.conv.weight'
Freezing layer 'model.7.bn.weight'
Freezing layer 'model.7.bn.bias'
Freezing layer 'model.8.cv1.conv.weight'
Freezing layer 'model.8.cv1.bn.weight'
Freezing layer 'model.8.cv1.bn.bias'
Freezing layer 'model.8.cv2.conv.weight'
Freezing layer 'model.8.cv2.bn.weight'
Freezing layer 'model.8.cv2.bn.bias'
Freezing layer 'model.8.m.0.cv1.conv.weight'
Freezing layer 'model.8.m.0.cv1.bn.weight'
Freezing layer 'model.8.m.0.cv1.bn.bias'
Freezing layer 'model.8.m.0.cv2.conv.weight'
Freezing layer 'model.8.m.0.cv2.bn.weight'
Freezing layer 'model.8.m.0.cv2.bn.bias'
Freezing layer 'model.8.m.0.cv3.conv.weight'
Freezing layer 'model.8.m.0.cv3.bn.weight'
Freezing layer 'model.8.m.0.cv3.bn.bias'
Freezing layer 'model.8.m.0.m.0.cv1.conv.weight'
Freezing layer 'model.8.m.0.m.0.cv1.bn.weight'
Freezing layer 'model.8.m.0.m.0.cv1.bn.bias'
Freezing layer 'model.8.m.0.m.0.cv2.conv.weight'
Freezing layer 'model.8.m.0.m.0.cv2.bn.weight'
Freezing layer 'model.8.m.0.m.0.cv2.bn.bias'
Freezing layer 'model.8.m.0.m.1.cv1.conv.weight'
Freezing layer 'model.8.m.0.m.1.cv1.bn.weight'
Freezing layer 'model.8.m.0.m.1.cv1.bn.bias'
Freezing layer 'model.8.m.0.m.1.cv2.conv.weight'
Freezing layer 'model.8.m.0.m.1.cv2.bn.weight'
Freezing layer 'model.8.m.0.m.1.cv2.bn.bias'
Freezing layer 'model.9.cv1.conv.weight'
Freezing layer 'model.9.cv1.bn.weight'
Freezing layer 'model.9.cv1.bn.bias'
Freezing layer 'model.9.cv2.conv.weight'
Freezing layer 'model.9.cv2.bn.weight'
Freezing layer 'model.9.cv2.bn.bias'
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26n.pt to 'yolo26n.pt': 100% ━━━━━━━━━━━━ 5.3MB 89.7MB/s 0.1s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 650.5±1160.1 MB/s, size: 829.7 KB)
train: Scanning /content/kitti3k_yolo/labels/train... 2100 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 2101/2101 197.9it/s 10.6s
train: New cache created: /content/kitti3k_yolo/labels/train.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
train: Caching images (0.7GB RAM): 100% ━━━━━━━━━━━━ 2101/2101 72.7it/s 28.9s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 144.0±113.9 MB/s, size: 775.0 KB)
val: Scanning /content/kitti3k_yolo/labels/val... 450 images, 2 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 452/452 105.6it/s 4.3s
val: New cache created: /content/kitti3k_yolo/labels/val.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
val: Caching images (0.2GB RAM): 100% ━━━━━━━━━━━━ 452/452 78.0it/s 5.8s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.001' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001429, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Plotting labels to /content/runs/detect/train/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/runs/detect/train
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20       1.5G      1.551      2.092      1.174         47        640: 100% ━━━━━━━━━━━━ 132/132 2.5it/s 52.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 1.7it/s 9.0s
                   all        452       2135      0.692      0.439      0.506      0.275

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20       1.5G      1.407      1.232      1.123         59        640: 100% ━━━━━━━━━━━━ 132/132 4.5it/s 29.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.4it/s 2.8s
                   all        452       2135      0.719      0.459      0.534      0.298

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/20       1.5G      1.375      1.126      1.097         49        640: 100% ━━━━━━━━━━━━ 132/132 4.9it/s 27.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 4.6it/s 3.3s
                   all        452       2135      0.577      0.524      0.551      0.309

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/20       1.5G      1.333      1.042      1.086         41        640: 100% ━━━━━━━━━━━━ 132/132 4.9it/s 26.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.4it/s 2.8s
                   all        452       2135        0.6      0.538      0.574      0.324

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/20       1.5G      1.296     0.9729       1.07         39        640: 100% ━━━━━━━━━━━━ 132/132 4.9it/s 27.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.1it/s 3.0s
                   all        452       2135      0.597      0.562      0.584      0.337

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/20       1.5G      1.271      0.934      1.054         53        640: 100% ━━━━━━━━━━━━ 132/132 4.8it/s 27.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 4.7it/s 3.2s
                   all        452       2135      0.738      0.498      0.612      0.362

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/20       1.5G      1.249     0.8934      1.042         21        640: 100% ━━━━━━━━━━━━ 132/132 4.8it/s 27.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.1it/s 2.9s
                   all        452       2135      0.716      0.569      0.622       0.36

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/20       1.5G      1.218     0.8624      1.036         49        640: 100% ━━━━━━━━━━━━ 132/132 4.7it/s 27.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.7it/s 2.7s
                   all        452       2135      0.736      0.545      0.629      0.363

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/20       1.5G      1.212     0.8481      1.026         28        640: 100% ━━━━━━━━━━━━ 132/132 4.7it/s 28.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.8it/s 2.6s
                   all        452       2135      0.755      0.553      0.645      0.388

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/20       1.5G      1.186     0.8236      1.017         45        640: 100% ━━━━━━━━━━━━ 132/132 4.5it/s 29.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 6.8it/s 2.2s
                   all        452       2135       0.72      0.578      0.646      0.393
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/20       1.5G      1.145     0.8233      1.008         27        640: 100% ━━━━━━━━━━━━ 132/132 4.5it/s 29.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.4it/s 2.0s
                   all        452       2135      0.734      0.568      0.633       0.37

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/20       1.5G       1.16     0.8063      1.013         39        640: 100% ━━━━━━━━━━━━ 132/132 4.8it/s 27.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.2it/s 2.1s
                   all        452       2135       0.72      0.572       0.64       0.38

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/20       1.5G      1.129     0.7708      1.005         13        640: 100% ━━━━━━━━━━━━ 132/132 4.9it/s 26.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 6.4it/s 2.4s
                   all        452       2135      0.762      0.564      0.651      0.377

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/20       1.5G      1.101     0.7503     0.9925         28        640: 100% ━━━━━━━━━━━━ 132/132 5.1it/s 25.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.4it/s 2.8s
                   all        452       2135       0.75      0.588      0.661      0.398

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/20       1.5G      1.082     0.7325      0.984         27        640: 100% ━━━━━━━━━━━━ 132/132 5.3it/s 25.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.5it/s 2.7s
                   all        452       2135        0.8      0.598       0.68      0.417

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/20       1.5G      1.073     0.7175     0.9765         19        640: 100% ━━━━━━━━━━━━ 132/132 5.2it/s 25.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 6.2it/s 2.4s
                   all        452       2135       0.85      0.584      0.677      0.417

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/20       1.5G      1.057      0.696     0.9739         22        640: 100% ━━━━━━━━━━━━ 132/132 5.0it/s 26.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.7it/s 2.0s
                   all        452       2135      0.793      0.616      0.691      0.418

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/20       1.5G       1.04     0.6832     0.9665         33        640: 100% ━━━━━━━━━━━━ 132/132 4.9it/s 26.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.2it/s 2.1s
                   all        452       2135      0.768      0.604      0.688       0.42

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/20       1.5G      1.028     0.6694     0.9653         28        640: 100% ━━━━━━━━━━━━ 132/132 4.8it/s 27.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.7it/s 2.0s
                   all        452       2135       0.83      0.606      0.696      0.434

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/20       1.5G      1.009     0.6573     0.9552         25        640: 100% ━━━━━━━━━━━━ 132/132 4.8it/s 27.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.5it/s 2.0s
                   all        452       2135      0.791      0.619      0.692      0.431

20 epochs completed in 0.177 hours.
Optimizer stripped from /content/runs/detect/train/weights/last.pt, 5.4MB
Optimizer stripped from /content/runs/detect/train/weights/best.pt, 5.4MB

Validating /content/runs/detect/train/weights/best.pt...
Ultralytics 8.4.116 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO11n summary (fused): 101 layers, 2,582,737 parameters, 0 gradients, 6.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 3.7it/s 4.1s

In [ ]:
import shutil
shutil.copy('/content/runs/detect/train/weights/best.pt',
            '/content/drive/MyDrive/config1_best.pt')
print('Model saved to Drive.')

Model saved to Drive.

In [ ]:
## 2ND CONFIGURATION

model_config2 = YOLO('yolo11n.pt')

train_results2 = model_config2.train(
    data=dataset_yaml,
    epochs=20,
    imgsz=640,
    batch=16,
    lr0=0.001,
    freeze=10,
    workers=2,
    cache='ram',
    device=0,
    exist_ok=True,
    pretrained=True,
    # augmentation targeting small/rare objects like cyclists
    degrees=15,
    scale=0.8,
    mosaic=1.0,
    copy_paste=0.3,
    mixup=0.1,
    name='train2'
)

print('Configuration 2 training complete.')

Ultralytics 8.4.116 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=ram, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.3, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/kitti3k_yolo/kitti3k.yaml, degrees=15, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=20, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=10, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.001, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.1, mode=train, model=yolo11n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train2, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/runs/detect/train2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.8, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    431257  ultralytics.nn.modules.head.Detect           [3, 16, None, [64, 128, 256]]
YOLO11n summary: 182 layers, 2,590,425 parameters, 2,590,409 gradients, 6.5 GFLOPs

Remapped 1/3 cls head rows from pretrained weights by class name
Transferred 451/499 items from pretrained weights
Freezing layer 'model.0.conv.weight'
Freezing layer 'model.0.bn.weight'
Freezing layer 'model.0.bn.bias'
Freezing layer 'model.1.conv.weight'
Freezing layer 'model.1.bn.weight'
Freezing layer 'model.1.bn.bias'
Freezing layer 'model.2.cv1.conv.weight'
Freezing layer 'model.2.cv1.bn.weight'
Freezing layer 'model.2.cv1.bn.bias'
Freezing layer 'model.2.cv2.conv.weight'
Freezing layer 'model.2.cv2.bn.weight'
Freezing layer 'model.2.cv2.bn.bias'
Freezing layer 'model.2.m.0.cv1.conv.weight'
Freezing layer 'model.2.m.0.cv1.bn.weight'
Freezing layer 'model.2.m.0.cv1.bn.bias'
Freezing layer 'model.2.m.0.cv2.conv.weight'
Freezing layer 'model.2.m.0.cv2.bn.weight'
Freezing layer 'model.2.m.0.cv2.bn.bias'
Freezing layer 'model.3.conv.weight'
Freezing layer 'model.3.bn.weight'
Freezing layer 'model.3.bn.bias'
Freezing layer 'model.4.cv1.conv.weight'
Freezing layer 'model.4.cv1.bn.weight'
Freezing layer 'model.4.cv1.bn.bias'
Freezing layer 'model.4.cv2.conv.weight'
Freezing layer 'model.4.cv2.bn.weight'
Freezing layer 'model.4.cv2.bn.bias'
Freezing layer 'model.4.m.0.cv1.conv.weight'
Freezing layer 'model.4.m.0.cv1.bn.weight'
Freezing layer 'model.4.m.0.cv1.bn.bias'
Freezing layer 'model.4.m.0.cv2.conv.weight'
Freezing layer 'model.4.m.0.cv2.bn.weight'
Freezing layer 'model.4.m.0.cv2.bn.bias'
Freezing layer 'model.5.conv.weight'
Freezing layer 'model.5.bn.weight'
Freezing layer 'model.5.bn.bias'
Freezing layer 'model.6.cv1.conv.weight'
Freezing layer 'model.6.cv1.bn.weight'
Freezing layer 'model.6.cv1.bn.bias'
Freezing layer 'model.6.cv2.conv.weight'
Freezing layer 'model.6.cv2.bn.weight'
Freezing layer 'model.6.cv2.bn.bias'
Freezing layer 'model.6.m.0.cv1.conv.weight'
Freezing layer 'model.6.m.0.cv1.bn.weight'
Freezing layer 'model.6.m.0.cv1.bn.bias'
Freezing layer 'model.6.m.0.cv2.conv.weight'
Freezing layer 'model.6.m.0.cv2.bn.weight'
Freezing layer 'model.6.m.0.cv2.bn.bias'
Freezing layer 'model.6.m.0.cv3.conv.weight'
Freezing layer 'model.6.m.0.cv3.bn.weight'
Freezing layer 'model.6.m.0.cv3.bn.bias'
Freezing layer 'model.6.m.0.m.0.cv1.conv.weight'
Freezing layer 'model.6.m.0.m.0.cv1.bn.weight'
Freezing layer 'model.6.m.0.m.0.cv1.bn.bias'
Freezing layer 'model.6.m.0.m.0.cv2.conv.weight'
Freezing layer 'model.6.m.0.m.0.cv2.bn.weight'
Freezing layer 'model.6.m.0.m.0.cv2.bn.bias'
Freezing layer 'model.6.m.0.m.1.cv1.conv.weight'
Freezing layer 'model.6.m.0.m.1.cv1.bn.weight'
Freezing layer 'model.6.m.0.m.1.cv1.bn.bias'
Freezing layer 'model.6.m.0.m.1.cv2.conv.weight'
Freezing layer 'model.6.m.0.m.1.cv2.bn.weight'
Freezing layer 'model.6.m.0.m.1.cv2.bn.bias'
Freezing layer 'model.7.conv.weight'
Freezing layer 'model.7.bn.weight'
Freezing layer 'model.7.bn.bias'
Freezing layer 'model.8.cv1.conv.weight'
Freezing layer 'model.8.cv1.bn.weight'
Freezing layer 'model.8.cv1.bn.bias'
Freezing layer 'model.8.cv2.conv.weight'
Freezing layer 'model.8.cv2.bn.weight'
Freezing layer 'model.8.cv2.bn.bias'
Freezing layer 'model.8.m.0.cv1.conv.weight'
Freezing layer 'model.8.m.0.cv1.bn.weight'
Freezing layer 'model.8.m.0.cv1.bn.bias'
Freezing layer 'model.8.m.0.cv2.conv.weight'
Freezing layer 'model.8.m.0.cv2.bn.weight'
Freezing layer 'model.8.m.0.cv2.bn.bias'
Freezing layer 'model.8.m.0.cv3.conv.weight'
Freezing layer 'model.8.m.0.cv3.bn.weight'
Freezing layer 'model.8.m.0.cv3.bn.bias'
Freezing layer 'model.8.m.0.m.0.cv1.conv.weight'
Freezing layer 'model.8.m.0.m.0.cv1.bn.weight'
Freezing layer 'model.8.m.0.m.0.cv1.bn.bias'
Freezing layer 'model.8.m.0.m.0.cv2.conv.weight'
Freezing layer 'model.8.m.0.m.0.cv2.bn.weight'
Freezing layer 'model.8.m.0.m.0.cv2.bn.bias'
Freezing layer 'model.8.m.0.m.1.cv1.conv.weight'
Freezing layer 'model.8.m.0.m.1.cv1.bn.weight'
Freezing layer 'model.8.m.0.m.1.cv1.bn.bias'
Freezing layer 'model.8.m.0.m.1.cv2.conv.weight'
Freezing layer 'model.8.m.0.m.1.cv2.bn.weight'
Freezing layer 'model.8.m.0.m.1.cv2.bn.bias'
Freezing layer 'model.9.cv1.conv.weight'
Freezing layer 'model.9.cv1.bn.weight'
Freezing layer 'model.9.cv1.bn.bias'
Freezing layer 'model.9.cv2.conv.weight'
Freezing layer 'model.9.cv2.bn.weight'
Freezing layer 'model.9.cv2.bn.bias'
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3225.5±907.9 MB/s, size: 822.4 KB)
train: Scanning /content/kitti3k_yolo/labels/train.cache... 2100 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 2101/2101 677.9Mit/s 0.0s
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
train: Caching images (0.7GB RAM): 100% ━━━━━━━━━━━━ 2101/2101 74.6it/s 28.2s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1769.8±1879.7 MB/s, size: 766.9 KB)
val: Scanning /content/kitti3k_yolo/labels/val.cache... 450 images, 2 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 452/452 21.8Mit/s 0.0s
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
val: Caching images (0.2GB RAM): 100% ━━━━━━━━━━━━ 452/452 57.0it/s 7.9s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.001' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001429, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Plotting labels to /content/runs/detect/train2/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/runs/detect/train2
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20      1.38G      1.857      2.365      1.328         56        640: 100% ━━━━━━━━━━━━ 132/132 4.0it/s 32.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 6.8it/s 2.2s
                   all        452       2135      0.585      0.418      0.417      0.186

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20      1.38G      1.665      1.458      1.254         38        640: 100% ━━━━━━━━━━━━ 132/132 4.3it/s 30.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 4.4it/s 3.4s
                   all        452       2135      0.626      0.427      0.467       0.22

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/20      1.38G      1.628      1.349      1.224         29        640: 100% ━━━━━━━━━━━━ 132/132 4.4it/s 30.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.0it/s 3.0s
                   all        452       2135      0.611      0.453      0.504      0.251

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/20      1.38G      1.577      1.268      1.209         63        640: 100% ━━━━━━━━━━━━ 132/132 4.4it/s 29.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 6.1it/s 2.5s
                   all        452       2135      0.636      0.476      0.526      0.272

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/20      1.38G       1.52      1.171       1.17         65        640: 100% ━━━━━━━━━━━━ 132/132 4.5it/s 29.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.9it/s 2.5s
                   all        452       2135      0.605      0.488      0.526      0.283

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/20      1.38G      1.501      1.135       1.16         50        640: 100% ━━━━━━━━━━━━ 132/132 4.4it/s 30.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 6.8it/s 2.2s
                   all        452       2135      0.695      0.508      0.563      0.297

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/20      1.38G      1.484      1.097      1.152         78        640: 100% ━━━━━━━━━━━━ 132/132 4.3it/s 30.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 3.7it/s 4.1s
                   all        452       2135      0.715      0.489      0.566      0.286

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/20      1.38G       1.44      1.071      1.142         39        640: 100% ━━━━━━━━━━━━ 132/132 4.2it/s 31.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 6.1it/s 2.4s
                   all        452       2135      0.668      0.543       0.58      0.305

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/20      1.38G      1.448      1.056      1.134         43        640: 100% ━━━━━━━━━━━━ 132/132 4.2it/s 31.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 6.0it/s 2.5s
                   all        452       2135      0.683       0.51      0.574        0.3

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/20      1.38G      1.432      1.035      1.129         59        640: 100% ━━━━━━━━━━━━ 132/132 4.2it/s 31.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 4.5it/s 3.3s
                   all        452       2135      0.649      0.534      0.587      0.331
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/20      1.54G      1.284     0.9452      1.086         27        640: 100% ━━━━━━━━━━━━ 132/132 4.6it/s 28.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.4it/s 2.8s
                   all        452       2135      0.726      0.519      0.609      0.318

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/20      1.54G      1.275     0.9196      1.081         39        640: 100% ━━━━━━━━━━━━ 132/132 5.3it/s 25.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 4.4it/s 3.4s
                   all        452       2135       0.72      0.488      0.589      0.319

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/20      1.54G      1.259     0.8942      1.078         13        640: 100% ━━━━━━━━━━━━ 132/132 5.3it/s 24.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.2it/s 2.9s
                   all        452       2135      0.709      0.568      0.627      0.344

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/20      1.54G      1.228     0.8737      1.062         27        640: 100% ━━━━━━━━━━━━ 132/132 5.3it/s 25.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 6.6it/s 2.3s
                   all        452       2135      0.789      0.504      0.625       0.34

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/20      1.54G      1.216     0.8557      1.058         27        640: 100% ━━━━━━━━━━━━ 132/132 5.1it/s 25.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.9it/s 1.9s
                   all        452       2135      0.722      0.528      0.622      0.356

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/20      1.54G      1.192     0.8321      1.051         19        640: 100% ━━━━━━━━━━━━ 132/132 4.9it/s 26.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.6it/s 2.0s
                   all        452       2135       0.72      0.588      0.645       0.36

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/20      1.54G      1.176     0.8187       1.05         22        640: 100% ━━━━━━━━━━━━ 132/132 4.7it/s 28.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.6it/s 2.0s
                   all        452       2135       0.74      0.572      0.645       0.35

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/20      1.54G      1.166     0.8046      1.033         32        640: 100% ━━━━━━━━━━━━ 132/132 4.9it/s 26.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.4it/s 2.0s
                   all        452       2135      0.716      0.593       0.65      0.374

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/20      1.54G       1.15     0.7913       1.03         28        640: 100% ━━━━━━━━━━━━ 132/132 5.0it/s 26.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.8it/s 1.9s
                   all        452       2135      0.748       0.57      0.656      0.373

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/20      1.54G      1.136     0.7695      1.019         25        640: 100% ━━━━━━━━━━━━ 132/132 5.0it/s 26.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.8it/s 1.9s
                   all        452       2135      0.744      0.568      0.654      0.373

20 epochs completed in 0.176 hours.
Optimizer stripped from /content/runs/detect/train2/weights/last.pt, 5.4MB
Optimizer stripped from /content/runs/detect/train2/weights/best.pt, 5.4MB

Validating /content/runs/detect/train2/weights/best.pt...
Ultralytics 8.4.116 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO11n summary (fused): 101 layers, 2,582,737 parameters, 0 gradients, 6.4 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 4.9it/s 3.1s
                   all        452       2135      0.713      0.589       0.65      0.373
               Cyclist         62         81      0.635      0.407      0.464      0.251
            Pedestrian         95        279      0.728      0.534      0.625      0.304
                   Car        408       1775      0.777      0.825      0.861      0.565
Speed: 0.1ms preprocess, 1.2ms inference, 0.0ms loss, 1.7ms postprocess per image
Results saved to /content/runs/detect/train2
Configuration 2 training complete.

In [ ]:
shutil.copy('/content/runs/detect/train2/weights/best.pt',
            '/content/drive/MyDrive/config2_best.pt')
print('Config 2 saved.')

Config 2 saved.

In [ ]:
## 3RD CONFIGURATON

model_config3 = YOLO('yolo11n.pt')

train_results3 = model_config3.train(
    data=dataset_yaml,
    epochs=40,
    imgsz=640,
    batch=16,
    lr0=0.001,
    freeze=0,
    workers=2,
    cache='ram',
    device=0,
    exist_ok=True,
    pretrained=True,
    cos_lr=True,
    name='train3'
)

print('Configuration 3 training complete.')

Ultralytics 8.4.116 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=ram, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=True, cutmix=0.0, data=/content/kitti3k_yolo/kitti3k.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=40, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.001, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train3, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/runs/detect/train3, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    431257  ultralytics.nn.modules.head.Detect           [3, 16, None, [64, 128, 256]]
YOLO11n summary: 182 layers, 2,590,425 parameters, 2,590,409 gradients, 6.5 GFLOPs

Remapped 1/3 cls head rows from pretrained weights by class name
Transferred 451/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 4042.6±730.2 MB/s, size: 822.4 KB)
train: Scanning /content/kitti3k_yolo/labels/train.cache... 2100 images, 1 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 2101/2101 677.9Mit/s 0.0s
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
train: Caching images (0.7GB RAM): 100% ━━━━━━━━━━━━ 2101/2101 72.8it/s 28.9s
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1562.0±1788.2 MB/s, size: 766.9 KB)
val: Scanning /content/kitti3k_yolo/labels/val.cache... 450 images, 2 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 452/452 16.2Mit/s 0.0s
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.
val: Caching images (0.2GB RAM): 100% ━━━━━━━━━━━━ 452/452 55.6it/s 8.1s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.001' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001429, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Plotting labels to /content/runs/detect/train3/labels.jpg...
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to /content/runs/detect/train3
Starting training for 40 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/40      2.36G      1.551        2.1      1.182         47        640: 100% ━━━━━━━━━━━━ 132/132 3.9it/s 33.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.4it/s 2.0s
                   all        452       2135      0.585      0.357      0.486      0.253

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/40      2.36G      1.415      1.251      1.132         59        640: 100% ━━━━━━━━━━━━ 132/132 4.1it/s 32.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.0it/s 3.0s
                   all        452       2135      0.475       0.43      0.432      0.242

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/40      2.36G      1.381      1.153      1.116         49        640: 100% ━━━━━━━━━━━━ 132/132 4.1it/s 32.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.4it/s 2.0s
                   all        452       2135      0.576      0.465       0.48      0.265

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/40      2.36G      1.346      1.064      1.109         41        640: 100% ━━━━━━━━━━━━ 132/132 4.2it/s 31.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.1it/s 2.1s
                   all        452       2135       0.57      0.536      0.534      0.299

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/40      2.36G      1.299     0.9907      1.085         39        640: 100% ━━━━━━━━━━━━ 132/132 4.2it/s 31.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.2it/s 2.1s
                   all        452       2135      0.697      0.468      0.542      0.306

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/40      2.36G      1.286     0.9613      1.075         53        640: 100% ━━━━━━━━━━━━ 132/132 4.1it/s 32.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.5it/s 2.7s
                   all        452       2135      0.669       0.53      0.584      0.339

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/40      2.36G      1.259     0.9095      1.067         21        640: 100% ━━━━━━━━━━━━ 132/132 4.2it/s 31.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.7it/s 2.0s
                   all        452       2135      0.708       0.53       0.58      0.335

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/40      2.36G      1.237     0.8924      1.059         49        640: 100% ━━━━━━━━━━━━ 132/132 4.2it/s 31.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.6it/s 2.0s
                   all        452       2135      0.641      0.515      0.568      0.334

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/40      2.36G      1.219      0.865      1.043         28        640: 100% ━━━━━━━━━━━━ 132/132 4.1it/s 32.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 6.3it/s 2.4s
                   all        452       2135       0.65      0.503       0.57      0.334

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/40      2.36G      1.194     0.8419      1.036         45        640: 100% ━━━━━━━━━━━━ 132/132 4.1it/s 32.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 6.0it/s 2.5s
                   all        452       2135      0.725      0.543      0.617      0.362

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/40      2.36G      1.191     0.8306      1.034         58        640: 100% ━━━━━━━━━━━━ 132/132 4.2it/s 31.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.7it/s 1.9s
                   all        452       2135      0.662      0.541      0.588      0.338

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/40      2.36G      1.167     0.8159      1.028         15        640: 100% ━━━━━━━━━━━━ 132/132 4.1it/s 32.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.6it/s 2.0s
                   all        452       2135      0.611      0.577      0.597      0.358

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/40      2.36G      1.147     0.7943      1.018         37        640: 100% ━━━━━━━━━━━━ 132/132 4.2it/s 31.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.8it/s 2.6s
                   all        452       2135      0.764      0.565       0.66      0.391

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/40      2.36G      1.164     0.7886       1.02         24        640: 100% ━━━━━━━━━━━━ 132/132 4.0it/s 32.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.3it/s 2.1s
                   all        452       2135      0.694       0.57      0.632      0.366

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/40      2.36G      1.115     0.7581      1.006         31        640: 100% ━━━━━━━━━━━━ 132/132 4.2it/s 31.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 6.8it/s 2.2s
                   all        452       2135      0.739      0.586      0.664      0.395

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/40      2.36G      1.108     0.7508      1.004         83        640: 100% ━━━━━━━━━━━━ 132/132 4.2it/s 31.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.5it/s 2.0s
                   all        452       2135      0.686       0.61      0.652      0.386

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/40      2.36G      1.097     0.7363     0.9983         49        640: 100% ━━━━━━━━━━━━ 132/132 4.1it/s 32.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.7it/s 2.7s
                   all        452       2135      0.772      0.595      0.683      0.409

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/40      2.36G      1.081     0.7263     0.9879         57        640: 100% ━━━━━━━━━━━━ 132/132 4.0it/s 32.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.3it/s 2.0s
                   all        452       2135      0.808      0.573      0.672      0.405

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/40      2.36G      1.075     0.7127     0.9887         77        640: 100% ━━━━━━━━━━━━ 132/132 4.2it/s 31.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.4it/s 2.0s
                   all        452       2135      0.755       0.64      0.698      0.422

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/40      2.36G      1.067     0.7017     0.9833         69        640: 100% ━━━━━━━━━━━━ 132/132 4.1it/s 32.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.2it/s 2.1s
                   all        452       2135      0.774      0.613      0.685      0.416

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/40      2.36G      1.051     0.6882     0.9779         12        640: 100% ━━━━━━━━━━━━ 132/132 4.0it/s 32.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.8it/s 2.6s
                   all        452       2135      0.799      0.607        0.7      0.434

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/40      2.36G      1.045     0.6867     0.9787         57        640: 100% ━━━━━━━━━━━━ 132/132 4.1it/s 32.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.7it/s 1.9s
                   all        452       2135      0.772      0.614       0.71      0.433

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/40      2.36G       1.04     0.6799     0.9722         71        640: 100% ━━━━━━━━━━━━ 132/132 4.1it/s 32.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.4it/s 2.0s
                   all        452       2135      0.761      0.643      0.716      0.442

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/40      2.36G      1.027      0.669     0.9658         21        640: 100% ━━━━━━━━━━━━ 132/132 4.0it/s 33.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.4it/s 2.8s
                   all        452       2135       0.81      0.637       0.72      0.439

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/40      2.36G      1.016     0.6576     0.9635         64        640: 100% ━━━━━━━━━━━━ 132/132 4.2it/s 31.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.3it/s 2.1s
                   all        452       2135      0.831      0.592      0.709       0.44

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/40      2.36G      1.007     0.6511     0.9596         41        640: 100% ━━━━━━━━━━━━ 132/132 4.1it/s 32.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.6it/s 2.0s
                   all        452       2135      0.759      0.652      0.723      0.447

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/40      2.36G     0.9927     0.6445     0.9573         52        640: 100% ━━━━━━━━━━━━ 132/132 4.2it/s 31.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 5.2it/s 2.9s
                   all        452       2135      0.791      0.652      0.733      0.466

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/40      2.36G     0.9813     0.6321     0.9507         39        640: 100% ━━━━━━━━━━━━ 132/132 4.1it/s 32.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.3it/s 2.1s
                   all        452       2135      0.833      0.609      0.719      0.451

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/40      2.36G      0.965     0.6195     0.9473         42        640: 100% ━━━━━━━━━━━━ 132/132 4.1it/s 31.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.5it/s 2.0s
                   all        452       2135      0.769      0.665      0.736      0.461

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/40      2.36G     0.9637     0.6232     0.9499         56        640: 100% ━━━━━━━━━━━━ 132/132 4.1it/s 31.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 6.3it/s 2.4s
                   all        452       2135      0.793       0.66       0.73      0.459
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/40      2.46G     0.9629     0.6192     0.9436         20        640: 100% ━━━━━━━━━━━━ 132/132 4.0it/s 33.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.3it/s 2.1s
                   all        452       2135      0.813      0.635      0.729      0.453

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/40      2.46G     0.9341     0.5976     0.9374         15        640: 100% ━━━━━━━━━━━━ 132/132 4.3it/s 30.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 15/15 7.7it/s 2.0s
                   all        452       2135      0.779      0.647      0.736      0.466

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      33/40      2.46G     0.9259     0.5855     0.9333         32        640: 100% ━━━━━━━━━━━━ 132/132 4.3it/s 30.3s

In [ ]:
shutil.copy('/content/runs/detect/train3/weights/best.pt',
            '/content/drive/MyDrive/config3_best.pt')
print('Config 3 saved.')

Config 3 saved.

In [ ]:
# table
import pandas as pd

summary = pd.DataFrame({
    'Configuration': ['Config 1 (Baseline)', 'Config 2 (Augmentation)', 'Config 3 (Full Unfreeze + Cosine LR)'],
    'Epochs': [20, 20, 40],
    'freeze': [10, 10, 0],
    'cos_lr': [False, False, True],
    'Augmentation': ['Default', 'degrees=15, scale=0.8, copy_paste=0.3, mixup=0.1', 'Default'],
    'Cyclist AP50': [0.549, 0.464, 0.616],
    'Cyclist AP50-95': [0.317, 0.251, 0.369],
    'Pedestrian AP50': [0.642, 0.625, 0.675],
    'Pedestrian AP50-95': [0.346, 0.304, 0.373],
    'Car AP50': [0.893, 0.861, 0.919],
    'Car AP50-95': [0.630, 0.565, 0.687],
    'mAP50': [0.695, 0.650, 0.736],
    'mAP50-95': [0.431, 0.373, 0.476],
})

summary

,Configuration,Epochs,freeze,cos_lr,Augmentation,Cyclist AP50,Cyclist AP50-95,Pedestrian AP50,Pedestrian AP50-95,Car AP50,Car AP50-95,mAP50,mAP50-95
0,Config 1 (Baseline),20,10,False,Default,0.549,0.317,0.642,0.346,0.893,0.630,0.695,0.431
1,Config 2 (Augmentation),20,10,False,"degrees=15, scale=0.8, copy_paste=0.3, mixup=0.1",0.464,0.251,0.625,0.304,0.861,0.565,0.650,0.373
2,Config 3 (Full Unfreeze + Cosine LR),40,0,True,Default,0.616,0.369,0.675,0.373,0.919,0.687,0.736,0.476

In [ ]:
## CONFIG OVERVIEW TABLE

config_table = pd.DataFrame({
    'Configuration': ['Config 1 (Baseline)', 'Config 2 (Augmentation)', 'Config 3 (Full Unfreeze + Cosine LR)'],
    'Epochs': [20, 20, 40],
    'Freeze': [10, 10, 0],
    'Cosine LR': [False, False, True],
    'Key Changes': ['Baseline as per brief', 'degrees=15, scale=0.8, copy_paste=0.3, mixup=0.1', 'freeze=0, epochs=40, cos_lr=True'],
})
config_table

,Configuration,Epochs,Freeze,Cosine LR,Key Changes
0,Config 1 (Baseline),20,10,False,Baseline as per brief
1,Config 2 (Augmentation),20,10,False,"degrees=15, scale=0.8, copy_paste=0.3, mixup=0.1"
2,Config 3 (Full Unfreeze + Cosine LR),40,0,True,"freeze=0, epochs=40, cos_lr=True"

In [ ]:
## RESULTS TABLE

results_table = pd.DataFrame({
    'Configuration': ['Config 1', 'Config 2', 'Config 3'],
    'Cyclist AP50': [0.549, 0.464, 0.616],
    'Cyclist AP50-95': [0.317, 0.251, 0.369],
    'Pedestrian AP50': [0.642, 0.625, 0.675],
    'Pedestrian AP50-95': [0.346, 0.304, 0.373],
    'Car AP50': [0.893, 0.861, 0.919],
    'Car AP50-95': [0.630, 0.565, 0.687],
    'mAP50': [0.695, 0.650, 0.736],
    'mAP50-95': [0.431, 0.373, 0.476],
})
results_table

,Configuration,Cyclist AP50,Cyclist AP50-95,Pedestrian AP50,Pedestrian AP50-95,Car AP50,Car AP50-95,mAP50,mAP50-95
0,Config 1,0.549,0.317,0.642,0.346,0.893,0.630,0.695,0.431
1,Config 2,0.464,0.251,0.625,0.304,0.861,0.565,0.650,0.373
2,Config 3,0.616,0.369,0.675,0.373,0.919,0.687,0.736,0.476

In [ ]:
## BEST (3RD) CONFIG VS TEST SET

# load best configuration 3 model
best_model = YOLO('/content/drive/MyDrive/config3_best.pt')

# evaluate on test set
test_metrics = best_model.val(
    data=dataset_yaml,
    split='test',
    imgsz=640,
    conf=0.001,
    iou=0.7,
    exist_ok=True,
    name='test_config3'
)

print('Test set results — Configuration 3 (Best):')
print(f'mAP50:    {test_metrics.box.map50:.3f}')
print(f'mAP50-95: {test_metrics.box.map:.3f}')

In [ ]:
## BEST (3RD) CONFIG VS TEST SET TABLE

comparison_table = pd.DataFrame({
    'Model': ['Pre-trained YOLO (no fine-tuning)', 'Config 3 (Fine-tuned, test set)'],
    'Car AP50': [0.713, 0.921],
    'Car AP50-95': [0.405, 0.692],
})
comparison_table